site_name: Company Docs Hub
site_url: https://github.com/nutanix-japan/docs-hub

theme:
  name: materialx
  features:
    - navigation.tabs
    - navigation.top

plugins:
  - search
  - multirepo:
      cleanup: true

nav:
  - Home: index.md
  - Hub and Spoke Setup:
    - Phase 1 - Hub: docs-hub-setup/phase1.md
    - Phase 2 - Hub: docs-hub-setup/phase2.md

extra:
  version:
    provider: mike